version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./jobs.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    volumes:
      - ./backend/data:/app/data
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: sqlite:latest
    volumes:
      - ./data/jobs.db:/data/jobs.db
    restart: unless-stopped

networks:
  default:
    driver: bridge

volumes:
  job_data: