apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-recruiter-secrets
  namespace: ai-agent-recruiter
  labels:
    app: ai-agent-recruiter
    component: secrets
type: Opaque
data:
  # OpenAI API Key (base64 encoded)
  OPENAI_API_KEY: ""  # Replace with base64 encoded API key
  
  # Email Configuration (base64 encoded)
  EMAIL_USERNAME: ""  # Replace with base64 encoded email username
  EMAIL_PASSWORD: ""  # Replace with base64 encoded email password
  
  # Database Credentials (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: ""  # Replace with base64 encoded database password
  POSTGRES_DB: YWlhZ2VudF9yZWNydWl0ZXI=  # aiagent_recruiter
  
  # JWT Secret Key (base64 encoded)
  JWT_SECRET_KEY: ""  # Replace with base64 encoded JWT secret
  
  # Encryption Key (base64 encoded)
  ENCRYPTION_KEY: ""  # Replace with base64 encoded encryption key
  
  # Third-party API Keys (base64 encoded)
  INDEED_API_KEY: ""  # Replace with base64 encoded Indeed API key
  LINKEDIN_API_KEY: ""  # Replace with base64 encoded LinkedIn API key
  DICE_API_KEY: ""  # Replace with base64 encoded Dice API key
  
  # Monitoring Credentials (base64 encoded)
  PROMETHEUS_USER: ""  # Replace with base64 encoded Prometheus user
  PROMETHEUS_PASSWORD: ""  # Replace with base64 encoded Prometheus password
  
  # Backup Configuration (base64 encoded)
  AWS_ACCESS_KEY_ID: ""  # Replace with base64 encoded AWS access key
  AWS_SECRET_ACCESS_KEY: ""  # Replace with base64 encoded AWS secret key
  S3_BUCKET_NAME: ""  # Replace with base64 encoded S3 bucket name
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-recruiter-secrets
  namespace: ai-agent-recruiter-staging
  labels:
    app: ai-agent-recruiter
    component: secrets
type: Opaque
data:
  # OpenAI API Key (base64 encoded)
  OPENAI_API_KEY: ""  # Replace with base64 encoded API key
  
  # Email Configuration (base64 encoded)
  EMAIL_USERNAME: ""  # Replace with base64 encoded email username
  EMAIL_PASSWORD: ""  # Replace with base64 encoded email password
  
  # Database Credentials (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: ""  # Replace with base64 encoded database password
  POSTGRES_DB: YWlhZ2VudF9yZWNydWl0ZXJfc3RhZ2luZw==  # aiagent_recruiter_staging
  
  # JWT Secret Key (base64 encoded)
  JWT_SECRET_KEY: ""  # Replace with base64 encoded JWT secret
  
  # Encryption Key (base64 encoded)
  ENCRYPTION_KEY: ""  # Replace with base64 encoded encryption key
  
  # Third-party API Keys (base64 encoded)
  INDEED_API_KEY: ""  # Replace with base64 encoded Indeed API key
  LINKEDIN_API_KEY: ""  # Replace with base64 encoded LinkedIn API key
  DICE_API_KEY: ""  # Replace with base64 encoded Dice API key
  
  # Monitoring Credentials (base64 encoded)
  PROMETHEUS_USER: ""  # Replace with base64 encoded Prometheus user
  PROMETHEUS_PASSWORD: ""  # Replace with base64 encoded Prometheus password
  
  # Backup Configuration (base64 encoded)
  AWS_ACCESS_KEY_ID: ""  # Replace with base64 encoded AWS access key
  AWS_SECRET_ACCESS_KEY: ""  # Replace with base64 encoded AWS secret key
  S3_BUCKET_NAME: ""  # Replace with base64 encoded S3 bucket name
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-agent-recruiter-secrets
  namespace: ai-agent-recruiter-dev
  labels:
    app: ai-agent-recruiter
    component: secrets
type: Opaque
data:
  # OpenAI API Key (base64 encoded)
  OPENAI_API_KEY: ""  # Replace with base64 encoded API key
  
  # Email Configuration (base64 encoded)
  EMAIL_USERNAME: ""  # Replace with base64 encoded email username
  EMAIL_PASSWORD: ""  # Replace with base64 encoded email password
  
  # Database Credentials (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: ""  # Replace with base64 encoded database password
  POSTGRES_DB: YWlhZ2VudF9yZWNydWl0ZXJfZGV2  # aiagent_recruiter_dev
  
  # JWT Secret Key (base64 encoded)
  JWT_SECRET_KEY: ""  # Replace with base64 encoded JWT secret
  
  # Encryption Key (base64 encoded)
  ENCRYPTION_KEY: ""  # Replace with base64 encoded encryption key
  
  # Third-party API Keys (base64 encoded)
  INDEED_API_KEY: ""  # Replace with base64 encoded Indeed API key
  LINKEDIN_API_KEY: ""  # Replace with base64 encoded LinkedIn API key
  DICE_API_KEY: ""  # Replace with base64 encoded Dice API key
  
  # Monitoring Credentials (base64 encoded)
  PROMETHEUS_USER: ""  # Replace with base64 encoded Prometheus user
  PROMETHEUS_PASSWORD: ""  # Replace with base64 encoded Prometheus password
  
  # Backup Configuration (base64 encoded)
  AWS_ACCESS_KEY_ID: ""  # Replace with base64 encoded AWS access key
  AWS_SECRET_ACCESS_KEY: ""  # Replace with base64 encoded AWS secret key
  S3_BUCKET_NAME: ""  # Replace with base64 encoded S3 bucket name